name: cj_flutter_riverpod_instagram_clone
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.16.0
  firebase_auth_platform_interface: ^7.0.9
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_dropzone: ^3.0.6
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  image_picker: ^1.0.4
  intl: any
  json_annotation: ^4.8.1
  mime: ^1.0.4
  smooth_page_indicator: ^1.1.0
  video_player: ^2.8.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          # weight: 400
