// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM80ksYWFyF2oWQaiHnUynwc7-wJ9mnyA',
    appId: '1:824733696034:web:996588119dcf4b7ad60a7b',
    messagingSenderId: '824733696034',
    projectId: 'cj-flutter-riverpod-instagram',
    authDomain: 'cj-flutter-riverpod-instagram.firebaseapp.com',
    storageBucket: 'cj-flutter-riverpod-instagram.appspot.com',
    measurementId: 'G-M3FN38GB2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVv-8MONKAB-jknZpkcekjg2PApQgEHxA',
    appId: '1:824733696034:android:85b236c710453b4dd60a7b',
    messagingSenderId: '824733696034',
    projectId: 'cj-flutter-riverpod-instagram',
    storageBucket: 'cj-flutter-riverpod-instagram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39GUu5_lAt3xGc4sFhetkWYCDLNASIYc',
    appId: '1:824733696034:ios:b06bc4446284c09bd60a7b',
    messagingSenderId: '824733696034',
    projectId: 'cj-flutter-riverpod-instagram',
    storageBucket: 'cj-flutter-riverpod-instagram.appspot.com',
    iosBundleId: 'com.example.cjFlutterRiverpodInstagramClone',
  );
}
